Vagrant.configure(2) do |config|
  #This box is poiting to a local box and will not work outside of my environment
  config.vm.box = "lcentos7"
  config.vm.hostname = "centos-lab"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "1024"
  end
end
